### ISSUE TITLE
Issues with BEDFile

### ISSUE THREAD

**Issue by saxovocal** [luskry/aptardi#12]
Dear aptardi team,

I have the following error when trying to build my own model:

```
*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
Traceback (most recent call last):
  File "/home/.conda/envs/aptardi/bin/aptardi", line 6, in <module>
    main()
  File "/home/.conda/envs/aptardi/lib/python3.7/site-packages/aptardi/aptardi.py", line 1913, in main
    ml_list = bi_di_format(ml_dict, names_of_columns)
  File "/home/.conda/envs/aptardi/lib/python3.7/site-packages/aptardi/aptardi.py", line 1405, in bi_di_format
    out_frame.columns = col_names
  File "/home/.conda/envs/aptardi/lib/python3.7/site-packages/pandas/core/generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/home/.conda/envs/aptardi/lib/python3.7/site-packages/pandas/core/generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/.conda/envs/aptardi/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/.conda/envs/aptardi/lib/python3.7/site-packages/pandas/core/internals/base.py", line 58, in _validate_set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 0 elements, new values have 28 elements

```

My BED file looks like this:
```
s1	139530	140594	ENST00000321264	-
s1	139530	140594	ENST00000321264	-
s1	162953	164089	ENST00000636051	-
s1	164261	164376	ENST00000636051	-
s1	165432	166029	ENST00000636051	-
s1	200072	200381	ENST00000305784	+
s1	202579	203872	ENST00000405546	-
```

And this is the command I ran
`aptardi --b $SORTEDBAM --f $FASTA --r $GTF --g $NEWGTF --m --e allpolyA_model.hdf5 --k allpolyA_scale.pk --s $POLYABED --l 0,4,1 --o $OUTPUTDIR`

The BED file was created according to the one you have proposed in the demo; and it does have column 4 (interpreting the error). Could you possibly point out what can be done to solve the problem? Thank you!

**Comment by saxovocal** [comment]
Hi all,

I have found a fix to this problem - the gtf, bam and bed files all need either "chr1" or "1"; not any other chromosome names. I would suggest others to remove other loose contigs as well. 

Another thing I found useful was to tailor the gtf file akin to a StringTie output. Hope this helps!
